name = "firstgame"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.63.0 and < 2.0.0"
tiramisu = ">= 1.0.0 and < 2.0.0" 
vec = ">= 3.0.1 and < 4.0.0"
lustre = ">= 5.3.5 and < 6.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 2.0.2 and <= 3.0.0"

[tools.lustre.html]
scripts = [
  { type = "importmap", content = "{ \"imports\": { \"three\": \"https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js\", \"three/addons/\": \"https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/\", \"@dimforge/rapier3d-compat\": \"https://cdn.jsdelivr.net/npm/@dimforge/rapier3d-compat@0.11.2/+esm\" } }" }
]
stylesheets = [
  { content = "body { margin: 0; padding: 0; overflow: hidden; }" },
  { content = "#app { position: fixed; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; z-index: 1000; }" }
]
