name = "flight_sim"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.63.0 and < 2.0.0"
tiramisu = { path = "../.." }
vec = ">= 3.0.1 and < 4.0.0"

[dev-dependencies]
lustre_dev_tools = ">= 2.0.2 and <= 3.0.0"

[tools.lustre.html]
scripts = [
  { type = "importmap", content = "{ \"imports\": { \"three\": \"https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js\", \"three/addons/\": \"https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/\", \"@dimforge/rapier3d-compat\": \"https://cdn.jsdelivr.net/npm/@dimforge/rapier3d-compat@0.11.2/+esm\" } }" }
]
stylesheets = [
  { content = "body { margin: 0; padding: 0; overflow: hidden; }" }
]
